### ISSUE TITLE
Add support for GNOME Shell 40

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/gnome-shell-user-stylesheet#1]

**Comment by jiri-one** [comment]
Now I switched to Fedora Linux 34 beta with Gnome 40 rc and now I am not happy without your extension working :). Please upgrade it :). And maybe you can add functionality to set my system font to calendar on top bar too, because that stupid little font is there still and again :). Thanks a lot for your work.

**Comment by TomaszGasior** [comment]
Workaround: `gsettings set org.gnome.shell disable-extension-version-validation true`
When I will fix this issue, please reset to defaults: `gsettings reset org.gnome.shell disable-extension-version-validation`

**Comment by TomaszGasior** [comment]
> And maybe you can add functionality to set my system font to calendar on top bar too, because that stupid little font is there still and again

I will take a look but I am trying to avoid coupling too much to shell stylesheet in the extension itself. You can try to resolve it youself using custom stylesheet and by looking into shell styles: https://github.com/TomaszGasior/gnome-shell-user-stylesheet#how-to-use-custom-style-sheet

**Comment by jiri-one** [comment]
![Screenshot from 2021-03-19 18-20-09](https://user-images.githubusercontent.com/32774109/111818782-dd7d6800-88df-11eb-878a-027fc8616149.png)
I am not able to do it dynamically, so my solution doesn't respect Large text settings from Accessibility menu, but it is better then nothing :D. Thanks for your help :). My solution it can be seen on screenshot or is here:
```
.calendar .calendar-day-base {
    font-size: 20px;
}
```

**Comment by TomaszGasior** [comment]
> I am not able to do it dynamically

Can't you use percents? :) We can add this to README in examples section.

**Comment by jiri-one** [comment]
Oh, nice idea :). Percents are working great and now it respects Large text settings from Accessibility menu and it is changed dynamically. 
```
.calendar .calendar-day-base {
    font-size: 100%;
}
```
