### ISSUE TITLE
App name not visible in Extensions app in Gnome 46

### ISSUE THREAD

**Issue by infeeeee** [TomaszGasior/gnome-shell-user-stylesheet#7]
Just an empty space instead of the name:

![kép](https://github.com/TomaszGasior/gnome-shell-user-stylesheet/assets/1271737/eef41757-b8ca-4592-83fc-2e2c458a2a91)

Steps to reproduce:
- Upgrade to Gnome 46
- Open Extensions app
- See the name of this extension is missing.

**Comment by TomaszGasior** [comment]
Reported here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7579
