### ISSUE TITLE
Gnome 47

### ISSUE THREAD

**Issue by KolbyML** [TomaszGasior/gnome-shell-user-stylesheet#9]
This extension is awesome would be great to have it updated for 47

**Comment by TomaszGasior** [comment]
Please create pull request to make that happen. Add 47 to "shell-version" in metadata.json and verify whether it works in 47. Also, increase "version" field.

**Comment by UlyssesZh** [comment]
Version 10 from extensions.gnome.org doesn't seem to support GNOME 47.

**Comment by TomaszGasior** [comment]
I've uploaded the extension for the second time. Let's wait for review then.
